name: 22.04 Ngx-php & PHP build test
on:
  workflow_call:

env:
  DB_DATABASE: ngx_php
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php_version: ["8.1.17"] #[7.0.33, 7.1.33, 7.2.34, 7.3.33, 7.4.26, 8.0.28, 8.1.17]
        ngxinx_version: ["1.22.1"] #[1.12.2, 1.20.2, 1.22.1, 1.24.0]
    steps:
    - uses: actions/checkout@v3
    - name: prepare basic packages
      run: | 
        sudo apt-get install -yqq locales language-pack-de re2c libgmp-dev libicu-dev libmcrypt-dev libtidy-dev libaspell-dev libpspell-dev librecode-dev libsasl2-dev libxpm-dev cpanminus openssl libssl-dev libbz2-dev libzip-dev systemtap-sdt-dev libonig-dev axel libcurl3-dev zlib1g-dev libpcre3-dev libargon2-0-dev libsodium-dev
        sudo apt-get install -y redis-server redis-tools memcached
        sudo redis-server /etc/redis/redis.conf
    - name: perl packages 
      run: sudo cpanm -n Test::Nginx
    - name: compiler
      env:
          PHP_SRC_VERSION: ${{ matrix.php_version }}
          NGINX_SRC_VERSION: ${{ matrix.ngxinx_version }}
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < .github/ngx-php/world.sql
        ./.github/ngx-php/compiler.sh
    - name: test
      run: ./.github/ngx-php/test.sh