name: Ngx-php build test
on:
  push:
    paths:
    - 'src/**'
    - 't/**'
    - 'third_party/**'
    - '.github/workfows/**'
    - '.travis/**'
  pull_request:
    paths: 
      - 'src/**'
      - 't/**'
      - 'third_party/**'
      - '.github/workfows/**'
      - '.travis/**'

env:
  DB_DATABASE: ngx_php
  DB_USER: root
  DB_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php_version: [7.4, '8.0', 8.1] #['7.0', 7.1, 7.2, 7.3, 7.4, '8.0', 8.1]
        ngxinx_version: [1.22.1, 1.23.4] #[1.12.2, 1.20.2, 1.22.1, 1.23.4]
        # Disable fail-fast to allow all failing versions to fail in a
        # single build, rather than stopping when the first one fails.
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: prepare basic packages
      run: | 
        sudo apt-get install -yqq locales language-pack-de re2c libgmp-dev libicu-dev libmcrypt-dev libtidy-dev libenchant-dev libaspell-dev libpspell-dev librecode-dev libsasl2-dev libxpm-dev cpanminus openssl libssl-dev libbz2-dev libzip-dev systemtap-sdt-dev libonig-dev axel libcurl3-dev zlib1g-dev libpcre3-dev libargon2-0-dev libsodium-dev libxml2-dev
        sudo apt-get install -y redis-server redis-tools memcached
        sudo redis-server /etc/redis/redis.conf
        sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
        sudo apt-get update -yqq >/dev/null && sudo apt-get upgrade -yqq >/dev/null
    - name: perl packages 
      run: sudo cpanm -n Test::Nginx
    - name: compiler
      env:
          PHP_SRC_VERSION: ${{ matrix.php_version }}
          NGINX_SRC_VERSION: ${{ matrix.ngxinx_version }}
      run: |
        echo "MySQL Start and create table"
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        if [ ! -d data-cache ]; then mkdir data-cache; fi
        if [ ! -f data-cache/world-db.tar.gz ]; then wget -O data-cache/world-db.tar.gz https://downloads.mysql.com/docs/world-db.tar.gz; fi
        tar zxvf data-cache/world-db.tar.gz
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < world-db/world.sql

        echo "Install PHP-${{ env.PHP_SRC_VERSION }}"
        sudo apt-get install php${{ env.PHP_SRC_VERSION }}-cli php${{ env.PHP_SRC_VERSION }}-dev libphp${{ env.PHP_SRC_VERSION }}-embed php${{ env.PHP_SRC_VERSION }}-mysql

        echo "Compile Ngx-php"  
        ./.travis/compile-ngx.sh
    - name: test
      run: ./.travis/test.sh
